project_id = "sandbox--spinnaker"
pubsub_topic = "gcr"
pubsub_subscription = "gcr-triggers"
region = "australia-southeast1"
release_name = "cd"
spinnaker_version = "1.14.0"
halyard_version = "1.22.2"
app_repo_name = "sample-app"
